version: '3'
services:
  boiler-plate:
    container_name: boiler-plate
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - .:/app
    tty: true
    env_file:
      - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo